# Generated by Django 5.2.16 on 2026-09-18 07:51

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_role_warehouseprofile'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseInventory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=apps.core.models.generate_public_id, editable=False, max_length=16, unique=True)),
                ('received_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dispatched_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(help_text='Unit of measurement (e.g., kg, L)', max_length=20)),
                ('storage_location', models.CharField(blank=True, help_text='e.g., Cold Room A', max_length=100)),
                ('storage_bin', models.CharField(blank=True, help_text='e.g., Shelf 1', max_length=50)),
                ('inventory_status', models.CharField(choices=[('RECEIVING', 'Receiving'), ('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('QUARANTINED', 'Quarantined'), ('DISPATCHED', 'Dispatched'), ('EXPIRED', 'Expired'), ('OUT_OF_STOCK', 'Out of Stock')], default='RECEIVING', max_length=20)),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date if applicable', null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('last_stock_update', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_inventory', to='suppliers.batch')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='accounts.warehouseprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movement_type', models.CharField(choices=[('RECEIVE', 'Receive'), ('RESERVE', 'Reserve'), ('RELEASE', 'Release'), ('DISPATCH', 'Dispatch'), ('ADJUSTMENT', 'Adjustment'), ('SPOILAGE', 'Spoilage'), ('EXPIRY', 'Expiry')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('warehouse_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='warehouse.warehouseinventory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
