# Generated by Django 5.2.16 on 2026-09-18 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('HOTEL', 'Hotel/Restaurant'), ('LAB', 'Lab'), ('SUPPLIER', 'Supplier/FPO'), ('ADMIN', 'Admin'), ('WAREHOUSE', 'Warehouse')], max_length=16),
        ),
        migrations.CreateModel(
            name='WarehouseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse_name', models.CharField(max_length=255)),
                ('warehouse_code', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=150)),
                ('contact_phone', models.CharField(max_length=20)),
                ('storage_type', models.CharField(help_text='e.g., Cold Storage, Dry Storage, etc.', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
